### PR TITLE
Add links to nodes

### PR DESCRIPTION
**Pull request by DrMattG**
One weird behaviour is that we get two nodes per input article. I need to look at that now. In the meantime how does this function for you? I think I am being a bit dumb as articles can be both reference and citation so for the inputs I need to get rid of the duplicates for the single column and not across all columns...

### CODE REVIEW

**Comment by DrMattG** [comment]
I added code to get rid of the duplicate inputs (with some terrible code - works but is awful)

**Comment by DrMattG** [comment]
Seen an error - need to remove the print()

**Comment by nealhaddaway** [comment]
Hmm - it renders the viz but then becomes unresponsive to directions to move around and the plot goes completely black. It makes me realise we need to build in a reset button to the network viz as well. Is it just mine that freezing and going black happens on?

**Comment by DrMattG** [comment]
Weird - it works for me but I am just using a small subset of dois - "I'm going to need a bigger network...." I will see if I can work out what is going wrong. Maybe my weird coding work around screwed things up.

**Comment by nealhaddaway** [comment]
Strange - I used 16 input articles.. and it works OK on the current shiny app... Maybe it's my local system tho. I'll try a reboot.
________________________________

**Pull request merged**
